[
    {
        "name": "AZlogD74",
        "attributes": {
            "observed_column": "ST00021 (LogD octanol pH 7.4);Mean;LogD (none)",
            "predicted_column": "AZlogD74;Earliest;prediction",
            "training_set_column": "AZlogD74;traintest",
            "model_version": "AZlogD74;Method Version; of Earliest prediction",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "linear",
            "plot_title": "AZlogD74",
            "pos_class": "<",
            "threshold": 3,
            "category": "PhysChem",
            "exp_error": 0.14,
            "heatmap_order": 1,
            "units": ""
        }
    },
    {
        "name": "Caco Efflux ratio",
        "attributes": {
            "observed_column": "ST00024 (Hu Caco2 Efflux);Mean;Efflux Ratio (none)",
            "predicted_column": "Caco2 Efflux;Earliest;Efflux Ratio",
            "training_set_column": "Caco2efflux;traintest",
            "model_version": "Caco2 Efflux;Method Version; of Earliest Efflux Ratio",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "Caco Efflux ratio",
            "pos_class": "<",
            "threshold": 10,
            "category": "Permeability",
            "exp_error": 0.15,
            "heatmap_order": 6,
            "units": ""
        }
    },
    {
        "name": "Caco2 Intrinsic Papp",
        "attributes": {
            "observed_column": "ST00216 (Caco-2 intrinsic permeability);Mean;A to B Papp (1E-6.cm/s)",
            "predicted_column": "Caco2 Intrinsic Papp;Earliest;Papp (1E-6cm/sec)",
            "training_set_column": "Caco2intr;traintest",
            "model_version": "Caco2 Intrinsic Papp;Method Version; of Earliest Papp (1E-6cm/sec)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "Intrinsic Caco",
            "pos_class": ">",
            "threshold": 5,
            "category": "Permeability",
            "exp_error": 0.16,
            "heatmap_order": 5,
            "units": "1E-6.cm/s"
        }
    },
    {
        "name": "ChromLogD",
        "attributes": {
            "observed_column": "IT28175 (Chrom LogD LCMS pH=7.4);Median;Chrom LogD (none)",
            "predicted_column": "ChromlogD;Earliest;prediction",
            "training_set_column": "ChromlogD;traintest",
            "model_version": "ChromlogD;Method Version; of Earliest prediction",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "linear",
            "plot_title": "ChromLogD",
            "pos_class": "<",
            "threshold": 5,
            "category": "PhysChem",
            "exp_error": 0.15,
            "heatmap_order": 2,
            "units": ""
        }
    },
    {
        "name": "DH CLint",
        "attributes": {
            "observed_column": "ST00030 (Dog Heps Met Clint);GMean;CLint (µl/min/1E6)",
            "predicted_column": "DH CLint;Earliest;prediction (μL/min/mg)",
            "training_set_column": "DHCLint;traintest",
            "model_version": "DH CLint;Method Version; of Earliest prediction (μL/min/mg)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "DH CLint",
            "pos_class": "<",
            "threshold": 10,
            "category": "Clint",
            "exp_error": 0.19,
            "heatmap_order": 10,
            "units": "µl/min/1E6"
        }
    },
    {
        "name": "dPPB",
        "attributes": {
            "observed_column": "ST00020 (Dog Protein Binding);Mean;Dog Prot binding (% free)",
            "predicted_column": "dPPB;Earliest;Percent Free (%)",
            "training_set_column": "dPPB;traintest",
            "model_version": "dPPB;Method Version; of Earliest Percent Free (%)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "dPPB",
            "pos_class": ">",
            "threshold": 1,
            "category": "PPB",
            "exp_error": 0.13,
            "heatmap_order": 15,
            "units": "%"
        }
    },
    {
        "name": "ePSA",
        "attributes": {
            "observed_column": "ST00260 (SFC ePSA (A2));Mean;ePSA (A2)  (none)",
            "predicted_column": "ePSA;Earliest;prediction (angstrom squared)",
            "training_set_column": "ePSA;traintest",
            "model_version": "ePSA;Method Version; of Earliest prediction (angstrom squared)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "linear",
            "plot_title": "ePSA",
            "pos_class": "<",
            "threshold": 150,
            "category": "PhysChem",
            "exp_error": 3.71,
            "heatmap_order": 3,
            "units": ""
        }
    },
    {
        "name": "FCS PPB",
        "attributes": {
            "observed_column": "ST00222 (FCS Protein Binding);Mean;FCS Prot binding (% free)",
            "predicted_column": "FCS PPB;Earliest;Percent Free (%)",
            "training_set_column": "FCS;traintest",
            "model_version": "FCS PPB;Method Version; of Earliest Percent Free (%)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "FCS PPB",
            "pos_class": ">",
            "threshold": 1,
            "category": "PPB",
            "exp_error": 0.11,
            "heatmap_order": 16,
            "units": "%"
        }
    },
    {
        "name": "hERG",
        "attributes": {
            "observed_column": "ST00231 (hERG IC50 Combined);GMean;IC50 (µM)",
            "predicted_column": "hERG;Earliest;IC50 (μM)",
            "training_set_column": "hERG;traintest",
            "model_version": "hERG;Method Version; of Earliest IC50 (μM)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "hERG",
            "pos_class": ">",
            "threshold": 10,
            "category": "Safety",
            "exp_error": 0.12,
            "heatmap_order": 11,
            "units": "µM"
        }
    },
    {
        "name": "HH CLint",
        "attributes": {
            "observed_column": "ST00028 (Human Heps Met Clint);GMean;CLint (µl/min/1E6)",
            "predicted_column": "HH CLint;Earliest;prediction (μL/min/1E6)",
            "training_set_column": "HHCLint;traintest",
            "model_version": "HH CLint;Method Version; of Earliest prediction (μL/min/1E6)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "HH CLint",
            "pos_class": "<",
            "threshold": 10,
            "category": "Clint",
            "exp_error": 0.14,
            "heatmap_order": 8,
            "units": "µl/min/1E6"
        }
    },
    {
        "name": "HLM CLint",
        "attributes": {
            "observed_column": "ST00025 (Hu Mics Metab);Mean;CLint (µl/min/mg)",
            "predicted_column": "HLM CLint;Earliest;prediction (μL/min/mg)",
            "training_set_column": "HLMCLint;traintest",
            "model_version": "HLM CLint;Method Version; of Earliest prediction (μL/min/mg)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "HLM CLint",
            "pos_class": "<",
            "threshold": 30,
            "category": "Clint",
            "exp_error": 0.14,
            "heatmap_order": 7,
            "units": "μL/min/mg"
        }
    },
    {
        "name": "hPPB",
        "attributes": {
            "observed_column": "ST00012 (Human Protein Binding);Mean;Human Prot binding (% free)",
            "predicted_column": "hPPB;Earliest;Percent Free (%)",
            "training_set_column": "hPPB;traintest",
            "model_version": "hPPB;Method Version; of Earliest Percent Free (%)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "hPPB",
            "pos_class": ">",
            "threshold": 1,
            "category": "PPB",
            "exp_error": 0.13,
            "heatmap_order": 12,
            "units": "%"
        }
    },
    {
        "name": "mPPB",
        "attributes": {
            "observed_column": "ST00013 (Mouse Protein Binding);Mean;Mouse Prot binding (% free)",
            "predicted_column": "mPPB;Earliest;Percent Free (%)",
            "training_set_column": "mPPB;traintest",
            "model_version": "mPPB;Method Version; of Earliest Percent Free (%)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "mPPB",
            "pos_class": ">",
            "threshold": 1,
            "category": "PPB",
            "exp_error": 0.11,
            "heatmap_order": 14,
            "units": "%"
        }
    },
    {
        "name": "RH CLint",
        "attributes": {
            "observed_column": "ST00027 (Rat Heps Met Clint);GMean;CLint (µl/min/1E6)",
            "predicted_column": "RH CLint;Earliest;prediction (μL/min/1E6)",
            "training_set_column": "RHCLint;traintest",
            "model_version": "RH CLint;Method Version; of Earliest prediction (μL/min/1E6)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "RH CLint",
            "pos_class": "<",
            "threshold": 10,
            "category": "Clint",
            "exp_error": 0.18,
            "heatmap_order": 9,
            "units": "µl/min/1E6"
        }
    },
    {
        "name": "RH Fuinc",
        "attributes": {
            "observed_column": "ST00210 (Rat Hep Fuinc);Mean;Unbound Fraction (%)",
            "predicted_column": "RH Fuinc;Earliest;Percent Free (%)",
            "training_set_column": "RHfuinc;traintest",
            "model_version": "RH Fuinc;Method Version; of Earliest Percent Free (%)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "RH Fuinc",
            "pos_class": ">",
            "threshold": 30,
            "category": "PPB",
            "exp_error": 0.06,
            "heatmap_order": 17,
            "units": "%"
        }
    },
    {
        "name": "rPPB",
        "attributes": {
            "observed_column": "ST00011 (Rat Protein Binding);Mean;Rat Prot binding (% free)",
            "predicted_column": "rPPB;Earliest;Percent Free (%)",
            "training_set_column": "rPPB;traintest",
            "model_version": "rPPB;Method Version; of Earliest Percent Free (%)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "rPPB",
            "pos_class": ">",
            "threshold": 1,
            "category": "PPB",
            "exp_error": 0.11,
            "heatmap_order": 13,
            "units": "%"
        }
    },
    {
        "name": "Solubility",
        "attributes": {
            "observed_column": "ST00271 (Solubility pH 7.4 (DMPK wave1));Mean;Solubility (µM)",
            "predicted_column": "Solubility DD;Earliest;prediction (μM)",
            "training_set_column": "SolubilityDD;traintest",
            "model_version": "Solubility DD;Method Version; of Earliest prediction (μM)",
            "sample_registration_date": "First Sample Registration Date",
            "plot_scale": "log",
            "plot_title": "Solubility",
            "pos_class": ">",
            "threshold": 50,
            "category": "PhysChem",
            "exp_error": 0.29,
            "heatmap_order": 4,
            "units": "µM"
        }
    }
]